### ISSUE TITLE
warningActions deprecated list

### ISSUE THREAD

**Issue by Kakifrucht** [BanManagement/BanManager#319]
How exactly does the new format work? The given list in the confiy.yml does not really make that clear. I have added cmd: to the list, however it still tells me I'm using the deprecated list.
Same thing for the hooks list, the example given produces invalid yml due to the missing : after the ban.

**Comment by confuser** [comment]
```yml
warningActions:
  enabled: false
  actions:
  '10':
    - cmd: ban [player] [reason]
      delay: 10
    - cmd: mute [player] [reason]
    - cmd: kick [player] [reason]
      delay: 20
```

**Comment by Kakifrucht** [comment]
So the only difference between the new format and the old format is the addition of cmd: and delay:?
As I said, I have added cmd: to the commands, not the delay: as I do not need it, but it still says it's deprecated.

**Comment by confuser** [comment]
Can you please post your warningActions. I did test the change extensively so I'm quite surprised you're getting the deprecated warning.

**Comment by Kakifrucht** [comment]
<pre>
warningActions:
  enabled: true
  actions:
    '4':
    - 'cmd: tempban [player] 4d 4 Verwarnungen (Letzte: [reason])'
    '5':
    - 'cmd: tempban [player] 5d 5 Verwarnungen (Letzte: [reason])'
    '6':
    - 'cmd: tempban [player] 10d 6 Verwarnungen (Letzte: [reason])'
    '7':
    - 'cmd: ban [player] 7 Verwarnungen (Letzte: [reason])'
</pre>

This however does not even work, as it not thinks it's an invalid command. This is probably due to the ' at the beginning and end, however I need them, otherwise the yaml would be invalid due to the colon.

**Comment by confuser** [comment]
It isn't a list, you can't do that, you need to use something like

```yaml
warningActions:
  enabled: true
  actions:
    '4':
    - cmd: 'tempban [player] 4d 4 Verwarnungen (Letzte: [reason])'
    '5':
    - cmd: 'tempban [player] 5d 5 Verwarnungen (Letzte: [reason])'
    '6':
    - cmd: 'tempban [player] 10d 6 Verwarnungen (Letzte: [reason])'
    '7':
    - 'cmd: 'ban [player] 7 Verwarnungen (Letzte: [reason])'
```

**Comment by Kakifrucht** [comment]
Thanks, this worked. Now I feel stupid, I thought I tried this.
And the hooks? How do I use them? This does not work:
<pre>
hooks:
  enabled: true
    warn:
     pre:
     - cmd: kick [player] [reason]
     post:
     - cmd: broadcast [player] banned
</pre>

**Comment by confuser** [comment]
```yaml
hooks:
  enabled: true
  events:
    warn:
      pre:
      - cmd: kick [player] [reason]
      post:
      - cmd: broadcast [player] banned
```
