### ISSUE TITLE
warn actions

### ISSUE THREAD

**Issue by EpiGame** [BanManagement/BanManager#718]
Um... How can I make custom actions for warn command ?

Example :
1st: kick + message
2nd: kick + message
3rd: kick + message
4th: tempban 30min + message
etc

Thank you :)

**Comment by confuser** [comment]
`config.yml`

```
# Commands to execute when a player reaches a certain number of warning points
warningActions:
  enabled: false
  actions:
    '1':
     - cmd: kick [player] message
    '2':
      - cmd: kick [player] message

```

etc
