### ISSUE TITLE
Make Global Database like Local Database

### ISSUE THREAD

**Issue by Maxetto** [BanManagement/BanManager#720]
**Tell us about your environment**
Spigot 1.8.8
ViaVersion 2.0.4
BanManager 5.13.1
5 Servers
BoNeMEAL Web Application
MySQL 5.6
Offline Mode

**BanManager config.yml**:
Hub:
```yaml
databases:
  local:
    enabled: true
    host: 127.0.0.1
    port: 3306
    name: bans
    user: username
    password: ''
    maxConnections: 10
    leakDetection: 3000
    tables:
      players: bm_players
      playerBans: bm_player_bans
      playerBanRecords: bm_player_ban_records
      playerMutes: bm_player_mutes
      playerMuteRecords: bm_player_mute_records
      playerKicks: bm_player_kicks
      playerNotes: bm_player_notes
      playerHistory: bm_player_history
      playerReports: bm_player_reports
      playerReportLocations: bm_player_report_locations
      playerReportStates: bm_player_report_states
      playerReportCommands: bm_player_report_commands
      playerReportComments: bm_player_report_comments
      playerWarnings: bm_player_warnings
      ipBans: bm_ip_bans
      ipBanRecords: bm_ip_ban_records
      ipMutes: bm_ip_mutes
      ipMuteRecords: bm_ip_mute_records
      ipRangeBans: bm_ip_range_bans
      ipRangeBanRecords: bm_ip_range_ban_records
      rollbacks: bm_rollbacks
      nameBans: bm_name_bans
      nameBanRecords: bm_name_ban_records
  global:
    enabled: false
    host: 127.0.0.1
    port: 3306
    name: bans
    user: username
    password: ''
    maxConnections: 10
    leakDetection: 3000
    tables:
      playerBans: bm_player_bans
      playerUnbans: bm_player_unbans
      playerMutes: bm_player_mutes
      playerUnmutes: bm_player_unmutes
      playerNotes: bm_player_notes
      ipBans: bm_ip_bans
      ipUnbans: bm_ip_unbans
```

Any other server:
```yaml
databases:
  local:
    enabled: true
    host: 127.0.0.1
    port: 3306
    name: bans
    user: username
    password: ''
    maxConnections: 10
    leakDetection: 3000
    tables:
      players: (servername)__bm_players
      playerBans: (servername)__bm_player_bans
      playerBanRecords: (servername)__bm_player_ban_records
      playerMutes: (servername)__bm_player_mutes
      playerMuteRecords: (servername)__bm_player_mute_records
      playerKicks: (servername)__bm_player_kicks
      playerNotes: (servername)__bm_player_notes
      playerHistory: (servername)__bm_player_history
      playerReports: (servername)__bm_player_reports
      playerReportLocations: (servername)__bm_player_report_locations
      playerReportStates: (servername)__bm_player_report_states
      playerReportCommands: (servername)__bm_player_report_commands
      playerReportComments: (servername)__bm_player_report_comments
      playerWarnings: (servername)__bm_player_warnings
      ipBans: (servername)__bm_ip_bans
      ipBanRecords: (servername)__bm_ip_ban_records
      ipMutes: (servername)__bm_ip_mutes
      ipMuteRecords: (servername)__bm_ip_mute_records
      ipRangeBans: (servername)__bm_ip_range_bans
      ipRangeBanRecords: (servername)__bm_ip_range_ban_records
      rollbacks: (servername)__bm_rollbacks
      nameBans: (servername)__bm_name_bans
      nameBanRecords: (servername)__bm_name_ban_records
  global:
    enabled: true
    host: 127.0.0.1
    port: 3306
    name: bans
    user: username
    password: ''
    maxConnections: 10
    leakDetection: 3000
    tables:
      playerBans: bm_player_bans
      playerUnbans: bm_player_unbans
      playerMutes: bm_player_mutes
      playerUnmutes: bm_player_unmutes
      playerNotes: bm_player_notes
      ipBans: bm_ip_bans
      ipUnbans: bm_ip_unbans
```

**Describe your issue:** 
I can't use Global Database if those tables are used as a Local Database. I thought it would be the same structure but with different table names, but it's not.

I'd like that global and local database structure are the same in order to allow mixed table management like that.

**How to replicate:** 
Use the same table names as local in a server and global in another.
 
**Further information:**
Even if it seems useless, I've been forced to do so because:
1) BoNeMEAL doesn't support global tables
2) There's no way to import bans from a server inside the global tables.
3) My Hub server is pretty much a global ban case, so there's no point in running global bans in there. All bans should be global, that's why its tables are used by other servers' global tables 

Thank you for your understanding.

P.S. Your Maven repo is offline and I can't build dev versions/try to fix it by myself.
