### ISSUE TITLE
Missing [expires] tag for Hooks

### ISSUE THREAD

**Issue by Maxetto** [BanManagement/BanManager#722]
Quick issue to let you know you can't hook a tempban due to no [expires] tag (or there is but it's undocumented).

I'd like to do this, but right now I can't:
```
hooks:
  enabled: true
  events:
    tempban:
      post:
      - cmd: tempbanip [player] [expires] [reason]
```
