### ISSUE TITLE
Players in database are stored too early

### ISSUE THREAD

**Issue by Maxetto** [BanManagement/BanManager#725]
# Issue report

**Tell us about your environment**
5 Servers
BoNeMEAL Web Application
MySQL 5.6

* **Server Software:**
Spigot
* **Server Version:**
1.8.8
* **BanManager Version:**
5.13.1

* **Online/Offline mode**: 
Offline Mode
* **Bungeecoord online/offline mode (if applicable)**: 
Offline Mode

**BanManager config.yml**:

```yaml

# 
# Aliases will be found and blocked automatically, e.g. msg will block tell
debug: false
databases:
  local:
    enabled: true
    host: 127.0.0.1
    port: 3306
    name: bans
    user: username
    password: password
    maxConnections: 10
    leakDetection: 3000
    tables:
      players: hub__bm_players
      playerBans: hub__bm_player_bans
      playerBanRecords: hub__bm_player_ban_records
      playerMutes: hub__bm_player_mutes
      playerMuteRecords: hub__bm_player_mute_records
      playerKicks: hub__bm_player_kicks
      playerNotes: hub__bm_player_notes
      playerHistory: hub__bm_player_history
      playerReports: hub__bm_player_reports
      playerReportLocations: hub__bm_player_report_locations
      playerReportStates: hub__bm_player_report_states
      playerReportCommands: hub__bm_player_report_commands
      playerReportComments: hub__bm_player_report_comments
      playerWarnings: hub__bm_player_warnings
      ipBans: hub__bm_ip_bans
      ipBanRecords: hub__bm_ip_ban_records
      ipMutes: hub__bm_ip_mutes
      ipMuteRecords: hub__bm_ip_mute_records
      ipRangeBans: hub__bm_ip_range_bans
      ipRangeBanRecords: hub__bm_ip_range_ban_records
      rollbacks: hub__bm_rollbacks
      nameBans: hub__bm_name_bans
      nameBanRecords: hub__bm_name_ban_records
  global:
    enabled: true
    host: 127.0.0.1
    port: 3306
    name: bans
    user: username
    password: password
    maxConnections: 10
    leakDetection: 3000
    tables:
      playerBans: bm_player_ban_all
      playerUnbans: bm_player_unban_all
      playerMutes: bm_player_mute_all
      playerUnmutes: bm_player_unmute_all
      playerNotes: bm_player_note_all
      ipBans: bm_ip_ban_all
      ipUnbans: bm_ip_unban_all
mutedCommandBlacklist:
- msg
softMutedCommandBlacklist:
- msg
duplicateIpCheck: true
bypassDuplicateChecks:
- 0.0.0.0
- 127.0.0.1
logKicks: true
logIps: false
displayNotifications: true
broadcastOnSync: true
timeLimits: {}
reportCooldown: 300
warningCooldown: 60
warningActions:
  enabled: true
  actions:
    '1':
    - cmd: tempbanall [player] 7d [reason]
    '2':
    - cmd: tempbanall [player] 14d [reason]
    '3':
    - cmd: banall [player] [reason]
warningMute: false
hooks:
  enabled: true
  events:
    ban:
      post:
      - cmd: banip [player] [reason]
    tempban:
      post:
      - cmd: tempbanip [player] [expires] [reason]
    unban:
      pre:
      - cmd: unbanip [player]
checkForUpdates: false
offlineAutoComplete: false
punishAlts: false
denyAlts: true
cleanUp:
  kicks: 30
  banRecords: 730
  ipBanRecords: 730
  ipMuteRecords: 90
  muteRecords: 90
  readWarnings: 180
  unreadWarnings: 180
maxOnlinePerIp: 0
checkOnJoin: true
createNoteReasons: false
onlineMode: false
chatPriority: normal

```

**Describe your issue:** 

Database player records are stored too early (during AsyncPlayerPreLoginEvent) and this means, in Offline Mode servers, that there are impossible player names in the database (not alphanumeric + underscore). Expecially spaces in player names makes the plugin show "duplicate record found" when the real name joins the server.

**How to replicate:** 

Join the server with an impossible nickname in Offline Mode with AuthMe Reloaded.
You should get kicked for invalid characters.
Check the BanManager player table, your name should appear even if it's useless since you couldn't join the server. 

**Further information:**

I'd suggest to use PlayerJoinEvent for creating the player record or make an option for it.
