### ISSUE TITLE
GDPR compliance: IP addresses are stored indefinitely

### ISSUE THREAD

**Issue by Foorack** [BanManagement/BanManager#766]
# Issue

We do have an interested in being alerted of users with the same IP as a banned player, which is why we have `logIps` true. However, it stores players IPs in `bm_player_history` indefinitely with no easy way of purging older entries (older than X days).

# Suggsetion
Add a `cleanUp` configuration for logged (but not necessarily banned) IP. If there already exists one then I'm sorry but I couldn't find it.

# Information
Our `bm_player_history` table has ~2,141,887 entries. :no_mouth: 
Current cleanUp options:
```yaml
# Keep records for number of days, use 0 to never delete
cleanUp:
  kicks: 30
  banRecords: 0
  ipBanRecords: 0
  ipMuteRecords: 0
  muteRecords: 0
  readWarnings: 0
  unreadWarnings: 0
```
