### ISSUE TITLE
Apparent connection leak detected

### ISSUE THREAD

**Issue by Mezy** [BanManagement/BanManager#769]
# Issue report

**Tell us about your environment**
A banned player try's to join the server, the server freezes and everyone gets kicked. (Log below)

* **Server Software:** Spigot
* **Server Version:** 1.8.8
* **BanManager Version:** 5.14.0 (I'm awear this isn't the latest version, if this bug has since been fixed please tell me.)

* **Online/Offline mode**: Offline
* **Bungeecoord online/offline mode (if applicable)**: Online

**BanManager config.yml**:

```yaml
# 
# Aliases will be found and blocked automatically, e.g. msg will block tell
debug: false
databases:
  local:
    enabled: true
    host: ***
    port: 3306
    name: ***
    user: ***
    password: ***
    maxConnections: 10
    leakDetection: 3000
    tables:
      players: bm_players
      playerBans: bm_player_bans
      playerBanRecords: bm_player_ban_records
      playerMutes: bm_player_mutes
      playerMuteRecords: bm_player_mute_records
      playerKicks: bm_player_kicks
      playerNotes: bm_player_notes
      playerHistory: bm_player_history
      playerReports: bm_player_reports
      playerReportLocations: bm_player_report_locations
      playerReportStates: bm_player_report_states
      playerReportCommands: bm_player_report_commands
      playerReportComments: bm_player_report_comments
      playerWarnings: bm_player_warnings
      ipBans: bm_ip_bans
      ipBanRecords: bm_ip_ban_records
      ipMutes: bm_ip_mutes
      ipMuteRecords: bm_ip_mute_records
      ipRangeBans: bm_ip_range_bans
      ipRangeBanRecords: bm_ip_range_ban_records
      rollbacks: bm_rollbacks
      nameBans: bm_name_bans
      nameBanRecords: bm_name_ban_records
  global:
    enabled: true
    host: ***
    port: 3306
    name: ***
    user: ***
    password: ***
    maxConnections: 10
    leakDetection: 3000
    tables:
      playerBans: bm_player_ban_all
      playerUnbans: bm_player_unban_all
      playerMutes: bm_player_mute_all
      playerUnmutes: bm_player_unmute_all
      playerNotes: bm_player_note_all
      ipBans: bm_ip_ban_all
      ipUnbans: bm_ip_unban_all
mutedCommandBlacklist:
- msg
- report
softMutedCommandBlacklist:
- msg
- report
duplicateIpCheck: true
bypassDuplicateChecks:
- 0.0.0.0
- 127.0.0.1
logKicks: true
logIps: true
displayNotifications: true
broadcastOnSync: false
timeLimits: {}
reportCooldown: 10
warningCooldown: 10
warningActions:
  enabled: false
warningMute: false
hooks:
  enabled: false
checkForUpdates: true
offlineAutoComplete: false
punishAlts: false
denyAlts: true
cleanUp:
  kicks: 30
  banRecords: 0
  ipBanRecords: 0
  ipMuteRecords: 0
  muteRecords: 0
  readWarnings: 0
  unreadWarnings: 0
maxOnlinePerIp: 0
checkOnJoin: false
createNoteReasons: false
onlineMode: true
chatPriority: normal

```

**Describe your issue:** 

Log: https://paste.md-5.net/dutocoyada.avrasm

**How to replicate:** I think it is when certain players join (Might have to do something with a hacked client)

 
**Further information:**
