### ISSUE TITLE
Duplicate "messages" for /tempban and /ban

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [BanManagement/BanManager#780]
# Issue report

**Tell us about your environment**

* **Server Software:** Spigot V1.12.2-R0.1-snapshot 
* **Server Version:** 1.12.2 
* **BanManager Version:**
5.15.0
* **Online/Offline mode**: 
* **Bungeecoord online/offline mode (if applicable)**: 
Online Bungee
**BanManager config.yml**:

```yaml
# 
# Aliases will be found and blocked automatically, e.g. msg will block tell
debug: false
databases:
  local:
    enabled: true
    host: 127.0.0.1
    port: 3306
    name: local_bans
    user: root
    password: 
    maxConnections: 10
    useSSL: false
    verifyServerCertificate: false
    leakDetection: 3000
    tables:
      players: bm_players
      playerBans: bm_player_bans
      playerBanRecords: bm_player_ban_records
      playerMutes: bm_player_mutes
      playerMuteRecords: bm_player_mute_records
      playerKicks: bm_player_kicks
      playerNotes: bm_player_notes
      playerHistory: bm_player_history
      playerReports: bm_player_reports
      playerReportLocations: bm_player_report_locations
      playerReportStates: bm_player_report_states
      playerReportCommands: bm_player_report_commands
      playerReportComments: bm_player_report_comments
      playerWarnings: bm_player_warnings
      ipBans: bm_ip_bans
      ipBanRecords: bm_ip_ban_records
      ipMutes: bm_ip_mutes
      ipMuteRecords: bm_ip_mute_records
      ipRangeBans: bm_ip_range_bans
      ipRangeBanRecords: bm_ip_range_ban_records
      rollbacks: bm_rollbacks
      nameBans: bm_name_bans
      nameBanRecords: bm_name_ban_records
  global:
    enabled: true
    host: 127.0.0.1
    port: 3306
    name: global_bans
    user: root
    password: 
    maxConnections: 10
    useSSL: false
    verifyServerCertificate: false
    leakDetection: 3000
    tables:
      playerBans: bm_player_ban_all
      playerUnbans: bm_player_unban_all
      playerMutes: bm_player_mute_all
      playerUnmutes: bm_player_unmute_all
      playerNotes: bm_player_note_all
      ipBans: bm_ip_ban_all
      ipUnbans: bm_ip_unban_all
mutedCommandBlacklist:
- msg
- pms
softMutedCommandBlacklist:
- msg
duplicateIpCheck: true
bypassDuplicateChecks:
- 192.168.1.6
logKicks: false
logIps: true
displayNotifications: true
broadcastOnSync: false
timeLimits: {}
reportCooldown: 10
warningCooldown: 10
warningActions:
  enabled: false
warningMute: false
hooks:
  enabled: false
checkForUpdates: true
offlineAutoComplete: true
punishAlts: false
denyAlts: false
cleanUp:
  kicks: 30
  banRecords: 0
  ipBanRecords: 0
  ipMuteRecords: 0
  muteRecords: 0
  readWarnings: 0
  unreadWarnings: 0
maxOnlinePerIp: 0
maxMultiaccountsRecently: 0
multiaccountsTime: 300
checkOnJoin: true
createNoteReasons: false
onlineMode: true
chatPriority: normal

Ensure you mask/remove any MySQL credentials!

```

**Describe your issue:** 

All this is with no edits to the messages.yml file and is across a bungee network (banned on hub server while test account is on another server - all linked with SQL)

Using /tempban [name][time][reason] results in the player being tempbanned, the chat announcement showing they have been tempbanned, but the message shown to player when kicked says "You have been permanently banned for [reason]
Editing the line under "ban" in the messages.yml titled "kick" (Red circle in image link below) modifies both the /ban and /tempban kick reasons. The "tempban" section below's "kick" message isn't used. (Green circle in image link below) 

https://i.imgur.com/ijzkNed.png

**How to replicate:** 

 Try tempban a player, the message on kick shows Permanently banned, when they attempt to join again, it tells them they have been temporarily banned and the time until the ban expires.
**Further information:**
