### ISSUE TITLE
Cannot connect do DB - Timezone issue

### ISSUE THREAD

**Issue by Iwitrag** [BanManagement/BanManager#787]
# Issue report
I have problem with DB connection on startup.

I get this error:

> [16:07:23] [Server thread/WARN]: Caused by: me.confuser.banmanager.internal.mysql.cj.exceptions.InvalidConnectionAttributeException: The server time zone value 'CEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.

 ```log here``` --> https://pastebin.com/41Rz0ax1

**Tell us about your environment**
I'm running server on remote hosting. I have contacted their support and they told me to contact plugin developer. They are unable to change timezone globally for 1 customer. All other plugins connecting to this database work well. Only BanManager does not.

* **Server Software:** Spigot
* **Server Version:** 1.14.2-R0.1-SNAPSHOT
* **BanManager Version:** 6.0.1

* **Online/Offline mode**: Tried both online / offline
* **Bungeecoord online/offline mode (if applicable)**: No bungee

**BanManager config.yml**: 
```yaml

  local:
    enabled: true
    storageType: mysql
    host: casa4.fakaheda.eu
    port: 3306
    name: 297318_mysql_db
    user: **********
    password: **********
    maxConnections: 3
    useSSL: false
    verifyServerCertificate: false
    leakDetection: 3000
    tables:
(all default)

```
