### ISSUE TITLE
/tempban not triggering PlayerUnbanEvent after ban time has passed

### ISSUE THREAD

**Issue by scpketer** [BanManagement/BanManager#791]
# Issue report

**Tell us about your environment**
Arch Linux x86; Java 8

* **Server Software:** Spigot
* **Server Version:** 1.14.3-R0.1
* **BanManager Version:** 6.0.2

* **Online/Offline mode**: Online
* **Bungeecoord online/offline mode (if applicable)**: Not running bungeecord.

**BanManager config.yml**:

```yaml
debug: false
databases:
  local:
    enabled: true
    storageType: mysql
    host: 127.0.0.1
    port: 3306
    name: local_bans
    user: [REDACTED]
    password: [REDACTED]
    maxConnections: 10
    useSSL: false
    verifyServerCertificate: false
    leakDetection: 3000
    tables:
      players: bm_players
      playerBans: bm_player_bans
      playerBanRecords: bm_player_ban_records
      playerMutes: bm_player_mutes
      playerMuteRecords: bm_player_mute_records
      playerKicks: bm_player_kicks
      playerNotes: bm_player_notes
      playerHistory: bm_player_history
      playerReports: bm_player_reports
      playerReportLocations: bm_player_report_locations
      playerReportStates: bm_player_report_states
      playerReportCommands: bm_player_report_commands
      playerReportComments: bm_player_report_comments
      playerWarnings: bm_player_warnings
      ipBans: bm_ip_bans
      ipBanRecords: bm_ip_ban_records
      ipMutes: bm_ip_mutes
      ipMuteRecords: bm_ip_mute_records
      ipRangeBans: bm_ip_range_bans
      ipRangeBanRecords: bm_ip_range_ban_records
      rollbacks: bm_rollbacks
      nameBans: bm_name_bans
      nameBanRecords: bm_name_ban_records
  global:
    enabled: false
    storageType: mysql
    host: 127.0.0.1
    port: 3306
    name: global_bans
    user: root
    password: ''
    maxConnections: 10
    useSSL: false
    verifyServerCertificate: false
    leakDetection: 3000
    tables:
      playerBans: bm_player_ban_all
      playerUnbans: bm_player_unban_all
      playerMutes: bm_player_mute_all
      playerUnmutes: bm_player_unmute_all
      playerNotes: bm_player_note_all
      ipBans: bm_ip_ban_all
      ipUnbans: bm_ip_unban_all
mutedCommandBlacklist:
- msg
softMutedCommandBlacklist:
- msg
duplicateIpCheck: true
bypassDuplicateChecks:
- 0.0.0.0
- 127.0.0.1
logKicks: false
logIps: true
displayNotifications: true
broadcastOnSync: false
timeLimits: {}
reportCooldown: 10
warningCooldown: 10
warningActions:
  enabled: false
warningMute: false
hooks:
  enabled: false
checkForUpdates: true
offlineAutoComplete: true
punishAlts: false
denyAlts: false
cleanUp:
  kicks: 30
  banRecords: 0
  ipBanRecords: 0
  ipMuteRecords: 0
  muteRecords: 0
  readWarnings: 0
  unreadWarnings: 0
maxOnlinePerIp: 0
maxMultiaccountsRecently: 0
multiaccountsTime: 300
checkOnJoin: false
createNoteReasons: false
onlineMode: true
chatPriority: normal

```

**Describe your issue:** 

I'm developing a plugin that depends on BanManager events. Sadly, temp bans are not triggering PlayerUnbanEvent when their time runs out.

**How to replicate:** 

Build some simple plugin that depends on BanManager with just PlayerBanEvent and PlayerUnbanEvent listeners. Trigger /tempban command on some player. Ensure that PlayerUnbanEvent is not called.
 
**Further information:**

 I could make a PR to this repo once I find out how to implement this.
