### ISSUE TITLE
Won't enable even with restart of server

### ISSUE THREAD

**Issue by lrmtheboss** [BanManagement/BanManager#815]
# Issue report

**Tell us about your environment**

* **Server Software:** Paper Spigot
* **Server Version:** 233 (MC: 1.14.4)
* **BanManager Version:** 6.0.2

* **Online/Offline mode**: Offline
* **Bungeecord online/offline mode (if applicable)**: Online (waterfall)

**BanManager config.yml**:

```yaml
# 
# Aliases will be found and blocked automatically, e.g. msg will block tell
debug: false
databases:
  local:
    storageType: mysql
    enabled: true
    host: 
    port: 
    name: 
    user: 
    password: 
    maxConnections: 2
    useSSL: false
    verifyServerCertificate: false
    leakDetection: 3000
    tables:
      players: bm_players
      playerBans: bm_player_bans
      playerBanRecords: bm_player_ban_records
      playerMutes: bm_player_mutes
      playerMuteRecords: bm_player_mute_records
      playerKicks: bm_player_kicks
      playerNotes: bm_player_notes
      playerHistory: bm_player_history
      playerReports: bm_player_reports
      playerReportLocations: bm_player_report_locations
      playerReportStates: bm_player_report_states
      playerReportCommands: bm_player_report_commands
      playerReportComments: bm_player_report_comments
      playerWarnings: bm_player_warnings
      ipBans: bm_ip_bans
      ipBanRecords: bm_ip_ban_records
      ipMutes: bm_ip_mutes
      ipMuteRecords: bm_ip_mute_records
      ipRangeBans: bm_ip_range_bans
      ipRangeBanRecords: bm_ip_range_ban_records
      rollbacks: bm_rollbacks
      nameBans: bm_name_bans
      nameBanRecords: bm_name_ban_records
  global:
    storageType: mysql
    enabled: true
    host: 
    port: 
    name: 
    user: 
    password: 
    maxConnections: 2
    useSSL: false
    verifyServerCertificate: false
    leakDetection: 3000
    tables:
      playerBans: bm_player_ban_all
      playerUnbans: bm_player_unban_all
      playerMutes: bm_player_mute_all
      playerUnmutes: bm_player_unmute_all
      playerNotes: bm_player_note_all
      ipBans: bm_ip_ban_all
      ipUnbans: bm_ip_unban_all
mutedCommandBlacklist:
- msg
- w
- r
- mail
- m
- t
- whisper
- emsg
- tell
- er
- reply
- ereply
- email
- action
- describe
- eme
- eaction
- edescribe
- etell
- ewhisper
- pm
softMutedCommandBlacklist:
- msg
- w
- r
- mail
- m
- t
- whisper
- emsg
- tell
- er
- reply
- ereply
- email
- action
- describe
- eme
- eaction
- edescribe
- etell
- ewhisper
- pm
duplicateIpCheck: true
bypassDuplicateChecks:
- 0.0.0.0
- 127.0.0.1
- 192.168.1.3
- 192.168.1.1
logKicks: true
logIps: true
displayNotifications: true
broadcastOnSync: false
timeLimits: {}
reportCooldown: 10
warningCooldown: 10
warningActions:
  enabled: false
warningMute: false
hooks:
  enabled: false
checkForUpdates: true
offlineAutoComplete: true
punishAlts: false
denyAlts: false
cleanUp:
  kicks: 0
  banRecords: 0
  ipBanRecords: 0
  ipMuteRecords: 0
  muteRecords: 0
  readWarnings: 0
  unreadWarnings: 0
maxOnlinePerIp: 3
maxMultiaccountsRecently: 0
multiaccountsTime: 300
checkOnJoin: true
createNoteReasons: true
onlineMode: true
chatPriority: normal

```

**Describe your issue:** 

It should start and work fine as it has in the past but when trying to use any BM commands in the console it gives "null" as its disabled. When trying to restart and/or reload it with plugman I get whats below. On server startup, I get what's in the 2nd area/box.

```plugman reload banmanager
[17:31:56 WARN]: Plugin BanManager v6.0.2 does not specify an api-version.
[17:31:56 INFO]: [BanManager] Enabling BanManager v6.0.2*
[17:31:56 ERROR]: Error occurred while enabling BanManager v6.0.2 (Is it up to date?)
java.lang.NoClassDefFoundError: me/confuser/banmanager/internal/sl4j/LoggerFactory
at me.confuser.banmanager.internal.hikari.HikariConfig.<clinit>(HikariConfig.java:51) ~[?:?]
at me.confuser.banmanager.BanManager.setupConnection(BanManager.java:316) ~[?:?]
at me.confuser.banmanager.BanManager.setupConnections(BanManager.java:306) ~[?:?]
at me.confuser.banmanager.BanManager.onEnable(BanManager.java:134) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-233]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-233]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-233]
at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366) ~[?:?]
at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318) ~[?:?]
at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:380) ~[?:?]
at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) ~[?:?]
at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.14.4.jar:git-Paper-233]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-233]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-233]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:701) ~[patched_1.14.4.jar:git-Paper-233]
at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:456) ~[patched_1.14.4.jar:git-Paper-233]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.4.jar:git-Paper-233]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-233]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-233]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: me.confuser.banmanager.internal.sl4j.LoggerFactory
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:109) ~[patched_1.14.4.jar:git-Paper-233]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.4.jar:git-Paper-233]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
... 21 more
Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
at java.util.zip.ZipFile.read(Native Method) ~[?:1.8.0_212]
at java.util.zip.ZipFile.access$1400(ZipFile.java:60) ~[?:1.8.0_212]
at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:734) ~[?:1.8.0_212]
at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:434) ~[?:1.8.0_212]
at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158) ~[?:1.8.0_212]
at java.io.FilterInputStream.read(FilterInputStream.java:107) ~[?:1.8.0_212]
at com.google.common.io.ByteStreams.copy(ByteStreams.java:106) ~[patched_1.14.4.jar:git-Paper-233]
at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:166) ~[patched_1.14.4.jar:git-Paper-233]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:107) ~[patched_1.14.4.jar:git-Paper-233]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.4.jar:git-Paper-233]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
... 21 more
[17:31:56 INFO]: [BanManager] Disabling BanManager v6.0.2
[17:31:56 INFO]: [PlugMan] BanManager has been reloaded.'''

'''[17:36:11 INFO]: [BanManager] Enabling BanManager v6.0.2*
[17:36:11 ERROR]: Error occurred while enabling BanManager v6.0.2 (Is it up to date?)
java.lang.NoClassDefFoundError: me/confuser/banmanager/internal/sl4j/LoggerFactory
at me.confuser.banmanager.internal.hikari.HikariConfig.<clinit>(HikariConfig.java:51) ~[?:?]
at me.confuser.banmanager.BanManager.setupConnection(BanManager.java:316) ~[?:?]
at me.confuser.banmanager.BanManager.setupConnections(BanManager.java:306) ~[?:?]
at me.confuser.banmanager.BanManager.onEnable(BanManager.java:134) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-233]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-233]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-233]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-233]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-233]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-233]
at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-233]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-233]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: me.confuser.banmanager.internal.sl4j.LoggerFactory
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:109) ~[patched_1.14.4.jar:git-Paper-233]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.4.jar:git-Paper-233]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
... 13 more
Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
at java.util.zip.ZipFile.read(Native Method) ~[?:1.8.0_212]
at java.util.zip.ZipFile.access$1400(ZipFile.java:60) ~[?:1.8.0_212]
at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:734) ~[?:1.8.0_212]
at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:434) ~[?:1.8.0_212]
at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158) ~[?:1.8.0_212]
at java.io.FilterInputStream.read(FilterInputStream.java:107) ~[?:1.8.0_212]
at com.google.common.io.ByteStreams.copy(ByteStreams.java:106) ~[patched_1.14.4.jar:git-Paper-233]
at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:166) ~[patched_1.14.4.jar:git-Paper-233]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:107) ~[patched_1.14.4.jar:git-Paper-233]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.4.jar:git-Paper-233]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
... 13 more
[17:36:11 INFO]: [BanManager] Disabling BanManager v6.0.2'''


<!--- If you have any BanManager related console output or BanManager seems -->
<!--- not to load at all provide us a FULL STARTUP LOG. -->
<!-- Please ensure this is wrapped in ```log here``` -->

**How to replicate:** 
<!--- If you can reproduce the issue please tell us in detail how -->
 
**Further information:**
<!--- Anything that you want to tell us that did not fit above can be put here -->
 On a side note where is the best place to download updates for this plugin at?

Thanks,
LRM
