### ISSUE TITLE
Add new-line placeholder in discord.yml messages

### ISSUE THREAD

**Issue by Nety01** [BanManagement/BanManager#833]

**Comment by confuser** [comment]
Try using `\n` for a new line

**Comment by Nety01** [comment]
Tried, didn't work

**Comment by confuser** [comment]
Can you provide an example of your discord.yml?

**Comment by Nety01** [comment]
```
# Requires DiscordSRV (Bukkit only)
enabled: true
punishments:
  ban:
    channel: punishment-log
    message: '```Hráč [player] byl permanentně zabanován adminem [actor].\nDůvod: [reason]```'
```

**Comment by confuser** [comment]
Use `"` instead, i.e.

```
# Requires DiscordSRV (Bukkit only)
enabled: true
punishments:
  ban:
    channel: punishment-log
    message: "```Hráč [player] byl permanentně zabanován adminem [actor].\nDůvod: [reason]```"
```
