### ISSUE TITLE
BMInfo permissions seem to be not working correctly

### ISSUE THREAD

**Issue by bigbluu722** [BanManagement/BanManager#892]
# Issue report

**Tell us about your environment**
Debian 10 dedicated linux machine, mysql database based.

* **Server Software:** Sponge
* **Server Version:** 1.12.2-2838-7.2.3
* **BanManager Version:** 7.2.2-sponge

* **Online/Offline mode**: Online
* **Bungeecoord online/offline mode (if applicable)**: N/A

**BanManager config.yml**:

```yaml

# 
# Aliases will be found and blocked automatically, e.g. msg will block tell
debug: false
databases:
  local:
    enabled: true
    storageType: mysql
    host: 127.0.0.1
    port: 3306
    name: <redacted>
    user: <redacted>
    password: <redacted>
    maxConnections: 10
    useSSL: false
    verifyServerCertificate: false
    leakDetection: 3000
    tables:
      players: bm_players
      playerBans: bm_player_bans
      playerBanRecords: bm_player_ban_records
      playerMutes: bm_player_mutes
      playerMuteRecords: bm_player_mute_records
      playerKicks: bm_player_kicks
      playerNotes: bm_player_notes
      playerHistory: bm_player_history
      playerReports: bm_player_reports
      playerReportLocations: bm_player_report_locations
      playerReportStates: bm_player_report_states
      playerReportCommands: bm_player_report_commands
      playerReportComments: bm_player_report_comments
      playerWarnings: bm_player_warnings
      ipBans: bm_ip_bans
      ipBanRecords: bm_ip_ban_records
      ipMutes: bm_ip_mutes
      ipMuteRecords: bm_ip_mute_records
      ipRangeBans: bm_ip_range_bans
      ipRangeBanRecords: bm_ip_range_ban_records
      rollbacks: bm_rollbacks
      nameBans: bm_name_bans
      nameBanRecords: bm_name_ban_records
  global:
    enabled: false
    storageType: mysql
    host: 127.0.0.1
    port: 3306
    name: global_bans
    user: root
    password: ''
    maxConnections: 10
    useSSL: false
    verifyServerCertificate: false
    leakDetection: 3000
    tables:
      playerBans: bm_player_ban_all
      playerUnbans: bm_player_unban_all
      playerMutes: bm_player_mute_all
      playerUnmutes: bm_player_unmute_all
      playerNotes: bm_player_note_all
      ipBans: bm_ip_ban_all
      ipUnbans: bm_ip_unban_all
mutedCommandBlacklist:
- msg
softMutedCommandBlacklist:
- msg
duplicateIpCheck: true
bypassDuplicateChecks:
- 0.0.0.0
- 127.0.0.1
logKicks: false
logIps: true
displayNotifications: true
broadcastOnSync: false
timeLimits: {}
cooldowns:
  ban: 10
  tempban: 10
  mute: 10
  tempmute: 10
  banip: 10
  tempbanip: 10
  warn: 10
  tempwarn: 10
  report: 10
warningCooldown: 10
warningActions:
  enabled: false
warningMute: false
hooks:
  enabled: false
checkForUpdates: true
offlineAutoComplete: true
punishAlts: false
denyAlts: false
cleanUp:
  kicks: 30
  banRecords: 0
  ipBanRecords: 0
  ipMuteRecords: 0
  muteRecords: 0
  readWarnings: 0
  unreadWarnings: 0
  playerHistory: 0
maxOnlinePerIp: 0
maxMultiaccountsRecently: 0
multiaccountsTime: 300
checkOnJoin: false
createNoteReasons: false
onlineMode: true
chatPriority: normal
blockInvalidReasons: false


```

**Describe your issue:** 

I've set bm.command.bminfo.connection and bm.command.bminfo.alts to false in my LuckPerms permissions for a specific user group, but they are still able to view ips and alts in /bminfo and /bminfo <user>

I've also set 
`apply-sponge-implicit-wildcards=false`

in the config for LuckPerms and that seemed to of not made a difference. 

**How to replicate:** 
 
N/A
 
**Further information:**

 Any help fixing this issue would be appreciated.
