### ISSUE TITLE
Silent flag doesn't work for unban commands

### ISSUE THREAD

**Issue by piotrskibapl** [BanManagement/BanManager#899]
# Issue report

**Tell us about your environment**

* **Server Software:** git-Paper-385
* **Server Version:** MC 1.15.2
* **BanManager Version:** 7.2.2

* **Online/Offline mode**: Offline
* **Bungeecoord online/offline mode (if applicable)**: Offline

**BanManager config.yml**:

```yaml

# 
# Aliases will be found and blocked automatically, e.g. msg will block tell
debug: false
databases:
  local:
    enabled: true
    storageType: hidden
    host: hidden
    port: hidden
    name: hidden
    user: hidden
    password: hidden
    maxConnections: hidden
    useSSL: hidden
    verifyServerCertificate: hidden
    leakDetection: hidden
    tables:
      players: hidden
      playerBans: hidden
      playerBanRecords: hidden
      playerMutes: hidden
      playerMuteRecords: hidden
      playerKicks: hidden
      playerNotes: hidden
      playerHistory: hidden
      playerReports: hidden
      playerReportLocations: hidden
      playerReportStates: hidden
      playerReportCommands: hidden
      playerReportComments: hidden
      playerWarnings: hidden
      ipBans: hidden
      ipBanRecords: hidden
      ipMutes: hidden
      ipMuteRecords: hidden
      ipRangeBans: hidden
      ipRangeBanRecords: hidden
      rollbacks: hidden
      nameBans: hidden
      nameBanRecords: hidden
  global:
    enabled: false
    storageType: mysql
    host: 127.0.0.1
    port: 3306
    name: global_bans
    user: root
    password: ''
    maxConnections: 10
    useSSL: false
    verifyServerCertificate: false
    leakDetection: 3000
    tables:
      playerBans: bm_player_ban_all
      playerUnbans: bm_player_unban_all
      playerMutes: bm_player_mute_all
      playerUnmutes: bm_player_unmute_all
      playerNotes: bm_player_note_all
      ipBans: bm_ip_ban_all
      ipUnbans: bm_ip_unban_all
mutedCommandBlacklist:
- msg
- w
- r
- message
- whisper
- tell
- vc
softMutedCommandBlacklist:
- msg
- w
- r
- message
- whisper
- tell
- vc
duplicateIpCheck: true
bypassDuplicateChecks:
- 0.0.0.0
- 127.0.0.1
logKicks: true
logIps: true
displayNotifications: true
broadcastOnSync: false
timeLimits: {}
cooldowns:
  ban: 5
  tempban: 5
  mute: 5
  tempmute: 5
  banip: 5
  tempbanip: 5
  warn: 5
  tempwarn: 5
  report: 0
warningCooldown: 5
warningActions:
  enabled: true
  actions:
    '2':
    - cmd: kick [player] [reason]
    '3':
    - cmd: tempban [player] 15m [reason]
    '4':
    - cmd: tempban [player] 1h [reason]
    '5':
    - cmd: tempban [player] 3h [reason]
    '6':
    - cmd: tempban [player] 6h [reason]
    '7':
    - cmd: tempban [player] 12h [reason]
warningMute: false
hooks:
  enabled: false
checkForUpdates: false
offlineAutoComplete: false
punishAlts: false
denyAlts: false
cleanUp:
  kicks: 0
  banRecords: 0
  ipBanRecords: 0
  ipMuteRecords: 0
  muteRecords: 0
  readWarnings: 0
  unreadWarnings: 0
  playerHistory: 0
maxOnlinePerIp: 0
maxMultiaccountsRecently: 0
multiaccountsTime: 300
checkOnJoin: false
createNoteReasons: false
onlineMode: false
chatPriority: normal
blockInvalidReasons: false


```

**Describe your issue:** 

Running the "/unban some_user -s" will send the notification to all users online.

**How to replicate:** 
1. Log in on the server
2. Execute "/banname test -s"
Observed: The notification about ban was not sent
3. Execute "/unbanname test -s"
Expected: The notification about unban should not be sent
Observed: The notification about unban was sent to all users online
