### ISSUE TITLE
Silent bans Discord

### ISSUE THREAD

**Issue by Majeranek777** [BanManagement/BanManager#920]
# Issue report

**Tell us about your environment**

* **Server Software:**
* **Server Version:**
* **BanManager Version:**
Paper 1.16.5 latest Ban Manager version
* **Offline mode**: 
offline mode
**BanManager config.yml**:

```yaml

# 
# Aliases will be found and blocked automatically, e.g. msg will block tell
debug: false
databases:
  local:
    enabled: true
    storageType: h2
    host: 127.0.0.1
    port: 3306
    name: local_bans
    user: root
    password: ''
    maxConnections: 10
    useSSL: false
    allowPublicKeyRetrieval: false
    verifyServerCertificate: false
    maxLifetime: 1800000
    connectionTimeout: 30000
    tables:
      players: bm_players
      playerBans: bm_player_bans
      playerBanRecords: bm_player_ban_records
      playerMutes: bm_player_mutes
      playerMuteRecords: bm_player_mute_records
      playerKicks: bm_player_kicks
      playerNotes: bm_player_notes
      playerHistory: bm_player_history
      playerReports: bm_player_reports
      playerReportLocations: bm_player_report_locations
      playerReportStates: bm_player_report_states
      playerReportCommands: bm_player_report_commands
      playerReportComments: bm_player_report_comments
      playerWarnings: bm_player_warnings
      ipBans: bm_ip_bans
      ipBanRecords: bm_ip_ban_records
      ipMutes: bm_ip_mutes
      ipMuteRecords: bm_ip_mute_records
      ipRangeBans: bm_ip_range_bans
      ipRangeBanRecords: bm_ip_range_ban_records
      rollbacks: bm_rollbacks
      nameBans: bm_name_bans
      nameBanRecords: bm_name_ban_records
  global:
    enabled: false
    storageType: mysql
    host: 127.0.0.1
    port: 3306
    name: global_bans
    user: root
    password: ''
    maxConnections: 10
    useSSL: false
    allowPublicKeyRetrieval: false
    verifyServerCertificate: false
    leakDetection: 3000
    maxLifetime: 1800000
    connectionTimeout: 30000
    tables:
      playerBans: bm_player_ban_all
      playerUnbans: bm_player_unban_all
      playerMutes: bm_player_mute_all
      playerUnmutes: bm_player_unmute_all
      playerNotes: bm_player_note_all
      ipBans: bm_ip_ban_all
      ipUnbans: bm_ip_unban_all
mutedCommandBlacklist:
- msg
softMutedCommandBlacklist:
- msg
duplicateIpCheck: true
bypassDuplicateChecks:
- 0.0.0.0
- 127.0.0.1
logKicks: false
logIps: true
displayNotifications: true
broadcastOnSync: false
timeLimits: {}
cooldowns:
  ban: 10
  tempban: 10
  mute: 10
  tempmute: 10
  banip: 10
  tempbanip: 10
  warn: 10
  tempwarn: 10
  report: 10
warningCooldown: 10
warningActions:
  enabled: false
warningMute: false
hooks:
  enabled: false
checkForUpdates: true
offlineAutoComplete: true
punishAlts: false
denyAlts: false
cleanUp:
  kicks: 30
  banRecords: 0
  ipBanRecords: 0
  ipMuteRecords: 0
  muteRecords: 0
  readWarnings: 0
  unreadWarnings: 0
  playerHistory: 0
maxOnlinePerIp: 3
maxMultiaccountsRecently: 5
multiaccountsTime: 300
checkOnJoin: false
createNoteReasons: false
onlineMode: false
chatPriority: normal
blockInvalidReasons: false
```

**Describe your issue:** 

Hello, i have a problem, i configured a discord bot to work with this plugin, everything worked just fine until i tried to use -s at the end, discord bot stopped logging silent bans etc. (non-silent stuff works fine). Is this a known problem or i just need to put something in my config? (i'm using paper 1.16.5 and DiscordSRV, both i installed yesterday 03.05.2021)

**How to replicate:** 
Silent ban someone with this option enabled.
 
**Further information:**

 If that's intended this would be a great thing to introduce, an option that you can switch on and off
