### ISSUE TITLE
timeAssociatedAlts as 0 doesn't work

### ISSUE THREAD

**Issue by Katrix** [BanManagement/BanManager#931]
# Issue report

**Tell us about your environment**

* **Server Software:** Paper
* **Server Version:** paper-1.16.5-779
* **BanManager Version:** 7.4.0

* **Online/Offline mode**: Online
* **Bungeecoord online/offline mode (if applicable)**: 

**BanManager config.yml**:
<details>

```yaml
# 
# Aliases will be found and blocked automatically, e.g. msg will block tell
debug: false
databases:
  local:
    enabled: true
    storageType: mysql
    host: 127.0.0.1
    port: 3306
    name: minecraft
    user: mine
    password: PingryAnimeFTW
    maxConnections: 10
    useSSL: false
    allowPublicKeyRetrieval: false
    verifyServerCertificate: false
    maxLifetime: 1800000
    connectionTimeout: 30000
    tables:
      players: bm_players
      playerBans: bm_player_bans
      playerBanRecords: bm_player_ban_records
      playerMutes: bm_player_mutes
      playerMuteRecords: bm_player_mute_records
      playerKicks: bm_player_kicks
      playerNotes: bm_player_notes
      playerHistory: bm_player_history
      playerReports: bm_player_reports
      playerReportLocations: bm_player_report_locations
      playerReportStates: bm_player_report_states
      playerReportCommands: bm_player_report_commands
      playerReportComments: bm_player_report_comments
      playerWarnings: bm_player_warnings
      ipBans: bm_ip_bans
      ipBanRecords: bm_ip_ban_records
      ipMutes: bm_ip_mutes
      ipMuteRecords: bm_ip_mute_records
      ipRangeBans: bm_ip_range_bans
      ipRangeBanRecords: bm_ip_range_ban_records
      rollbacks: bm_rollbacks
      nameBans: bm_name_bans
      nameBanRecords: bm_name_ban_records
    leakDetection: 3000
  global:
    enabled: false
    storageType: mysql
    host: 127.0.0.1
    port: 3306
    name: global_bans
    user: root
    password: ''
    maxConnections: 10
    useSSL: false
    allowPublicKeyRetrieval: false
    verifyServerCertificate: false
    leakDetection: 3000
    maxLifetime: 1800000
    connectionTimeout: 30000
    tables:
      playerBans: bm_player_ban_all
      playerUnbans: bm_player_unban_all
      playerMutes: bm_player_mute_all
      playerUnmutes: bm_player_unmute_all
      playerNotes: bm_player_note_all
      ipBans: bm_ip_ban_all
      ipUnbans: bm_ip_unban_all
mutedCommandBlacklist:
- msg
softMutedCommandBlacklist:
- msg
duplicateIpCheck: true
bypassDuplicateChecks:
- 0.0.0.0
- 127.0.0.1
logKicks: false
logIps: true
displayNotifications: true
broadcastOnSync: false
timeLimits: {}
cooldowns:
  ban: 10
  tempban: 10
  mute: 10
  tempmute: 10
  banip: 10
  tempbanip: 10
  warn: 10
  tempwarn: 10
  report: 10
warningActions:
  enabled: false
warningMute: false
hooks:
  enabled: false
checkForUpdates: true
offlineAutoComplete: true
punishAlts: false
denyAlts: false
timeAssociatedAlts: 0
cleanUp:
  kicks: 30
  banRecords: 0
  ipBanRecords: 0
  ipMuteRecords: 0
  muteRecords: 0
  readWarnings: 0
  unreadWarnings: 0
  playerHistory: 0
maxOnlinePerIp: 0
maxMultiaccountsRecently: 0
multiaccountsTime: 300
checkOnJoin: false
createNoteReasons: false
onlineMode: true
chatPriority: normal
blockInvalidReasons: false
uuidFetcher:
  idToName:
    url: https://sessionserver.mojang.com/session/minecraft/profile/[uuid]
    key: name
  nameToId:
    url: https://api.mojang.com/users/profiles/minecraft/[name]
    key: id
warningCooldown: 10
reportCooldown: 10
```

</details>

**Describe your issue:** 
No users show up when using the /alts command, not even the user I tried to look it up for.

**How to replicate:** 
1. Run /alts for a user.
2. No alts found, not even the user I tried to find alts for.
3. Increased `timeAssociatedAlts` so it's not 0 (I set one year, 378432000) and reload
4. Run the alts command again. It works
 
**Further information:**
According to [this](https://github.com/BanManagement/BanManager/blob/master/common/src/main/resources/config.yml#L173), setting timeAssociatedAlts should make them always be associated, but that doesn't seem to work.
